Document: ignite-app
Title: Debian ignite-app Manual
Author: <insert document author here>
Abstract: This manual describes what ignite-app is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ignite-app/ignite-app.sgml.gz

Format: postscript
Files: /usr/share/doc/ignite-app/ignite-app.ps.gz

Format: text
Files: /usr/share/doc/ignite-app/ignite-app.text.gz

Format: HTML
Index: /usr/share/doc/ignite-app/html/index.html
Files: /usr/share/doc/ignite-app/html/*.html
